In [1]:
import sys
from pathlib import Path

project_root = Path("../")

sys.path.append(str(project_root))

In [2]:
from src.parser.log_parser import load_and_parse_logs
df = load_and_parse_logs(
    "../data/raw/Hadoop_2k.log",
    "../data/processed/Hadoop_2k_structured.csv"
)

In [3]:
df.head()

,Date,Time,Level,Process,Component,Content,LineId
0,2015-10-18,"18:01:47,978",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,Created MRAppMaster for application appattempt...,1
1,2015-10-18,"18:01:48,963",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,Executing with tokens:,2
2,2015-10-18,"18:01:48,963",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,"Kind: YARN_AM_RM_TOKEN, Service: , Ident: (app...",3
3,2015-10-18,"18:01:49,228",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,Using mapred newApiCommitter.,4
4,2015-10-18,"18:01:50,353",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,OutputCommitter set in config null,5

In [4]:
from src.processing.counters import (
    count_phrase_occurrences,
    count_log_levels
)

count_log_levels(df)

Level
INFO     1040
WARN      808
ERROR     150
FATAL       2
Name: count, dtype: int64

In [5]:
count_phrase_occurrences(
    df,
    "Content",
    "Registering"
)

np.int64(9)

In [6]:
from src.processing.filters import (
    filter_by_log_level,
    filter_by_date_range,
    filter_by_phrase,
)

In [7]:
errors = filter_by_log_level(
    df,
    "ERROR"
)

errors.head()

,Date,Time,Level,Process,Component,Content,LineId
667,2015-10-18,"18:04:11,034",ERROR,RMCommunicator Allocator,org.apache.hadoop.mapreduce.v2.app.rm.RMContai...,Container complete event for unknown container...,668
922,2015-10-18,"18:06:01,840",ERROR,RMCommunicator Allocator,org.apache.hadoop.mapreduce.v2.app.rm.RMContai...,ERROR IN CONTACTING RM.,923
930,2015-10-18,"18:06:03,856",ERROR,RMCommunicator Allocator,org.apache.hadoop.mapreduce.v2.app.rm.RMContai...,ERROR IN CONTACTING RM.,931
937,2015-10-18,"18:06:05,934",ERROR,RMCommunicator Allocator,org.apache.hadoop.mapreduce.v2.app.rm.RMContai...,ERROR IN CONTACTING RM.,938
946,2015-10-18,"18:06:07,950",ERROR,RMCommunicator Allocator,org.apache.hadoop.mapreduce.v2.app.rm.RMContai...,ERROR IN CONTACTING RM.,947

In [8]:
info_logs = filter_by_log_level(
    df,
    "INFO"
)

info_logs.head()

,Date,Time,Level,Process,Component,Content,LineId
0,2015-10-18,"18:01:47,978",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,Created MRAppMaster for application appattempt...,1
1,2015-10-18,"18:01:48,963",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,Executing with tokens:,2
2,2015-10-18,"18:01:48,963",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,"Kind: YARN_AM_RM_TOKEN, Service: , Ident: (app...",3
3,2015-10-18,"18:01:49,228",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,Using mapred newApiCommitter.,4
4,2015-10-18,"18:01:50,353",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,OutputCommitter set in config null,5

In [9]:
filtered_dates = filter_by_date_range(
    df,
    "2015-10-18",
    "2015-10-18"
)

filtered_dates.head()

,Date,Time,Level,Process,Component,Content,LineId
0,2015-10-18,"18:01:47,978",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,Created MRAppMaster for application appattempt...,1
1,2015-10-18,"18:01:48,963",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,Executing with tokens:,2
2,2015-10-18,"18:01:48,963",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,"Kind: YARN_AM_RM_TOKEN, Service: , Ident: (app...",3
3,2015-10-18,"18:01:49,228",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,Using mapred newApiCommitter.,4
4,2015-10-18,"18:01:50,353",INFO,main,org.apache.hadoop.mapreduce.v2.app.MRAppMaster,OutputCommitter set in config null,5

In [10]:
registering_logs = filter_by_phrase(
    df,
    "Content",
    "Registering"
)

registering_logs.head()

,Date,Time,Level,Process,Component,Content,LineId
6,2015-10-18,"18:01:50,556",INFO,main,org.apache.hadoop.yarn.event.AsyncDispatcher,Registering class org.apache.hadoop.mapreduce....,7
7,2015-10-18,"18:01:50,556",INFO,main,org.apache.hadoop.yarn.event.AsyncDispatcher,Registering class org.apache.hadoop.mapreduce....,8
8,2015-10-18,"18:01:50,556",INFO,main,org.apache.hadoop.yarn.event.AsyncDispatcher,Registering class org.apache.hadoop.mapreduce....,9
9,2015-10-18,"18:01:50,556",INFO,main,org.apache.hadoop.yarn.event.AsyncDispatcher,Registering class org.apache.hadoop.mapreduce....,10
10,2015-10-18,"18:01:50,572",INFO,main,org.apache.hadoop.yarn.event.AsyncDispatcher,Registering class org.apache.hadoop.mapreduce....,11